### ISSUE TITLE
Add configuration via config file

### ISSUE THREAD

**Issue by dcrowe** [Visual-Regression-Tracker/sdk-python#18]
Read file vrt.json from project root with structure:

```
{
      "apiUrl": "http://162.243.161.172:4200",
      "project": "VRT",
      "apiKey": "SECRET",
      "branchName": "master",
      "enableSoftAssert": false,
      "ciBuildId": "SOME_UNIQUE_ID"
}
```

env variables example:
```
VRT_APIURL="http://localhost:4200" 
VRT_PROJECT="Default project" 
VRT_APIKEY="tXZVHX0EA4YQM1MGDD" 
VRT_CIBUILDID="commit_sha" 
VRT_BRANCHNAME="develop" 
VRT_ENABLESOFTASSERT=true
```

Acceptance criteria:
- [x]  config variables are read from config file
- [x]  can start build with default constructor VisualRegressionTracker (without specific config)
- [x]  validation error is thrown in case required config properties are not set
- [x]  explicit config from code is overriding values from env variables
- [x]  env variables are overriding values from config file

**Comment by dcrowe** [comment]
Have also updated examples here: https://github.com/Visual-Regression-Tracker/examples-python/pull/3

**Comment by pashidlos** [comment]
you did it already with env variables 👍 
gonna include it into other SDKs AC
