### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'playwright.sync_api'

### ISSUE THREAD

**Issue by stp4k** [Visual-Regression-Tracker/sdk-python#23]
After playwright version [https://github.com/microsoft/playwright-python/releases/tag/v0.171.1](v0.171.1) when running example: https://github.com/Visual-Regression-Tracker/examples-python/tree/master/playwright error occurs:

`Traceback (most recent call last):
  File "**path_to_project**/examples-python/playwright/example.py", line 8, in <module>
    from visual_regression_tracker.playwright import PlaywrightVisualRegressionTracker, PageTrackOptions, \
  File "**path_to_env**/lib/python3.8/site-packages/visual_regression_tracker/playwright.py", line 7, in <module>
    from playwright.sync_api import Literal, FloatRect
ImportError: cannot import name 'Literal' from 'playwright.sync_api'`

**Comment by pashidlos** [comment]
will be fixed by https://github.com/Visual-Regression-Tracker/sdk-python/issues/21

**Comment by pashidlos** [comment]
@schurakov  fixed in `4.8.0`
